version: '3.6'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-docker-template
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: 'nodemon'
    entrypoint: ["/app/entrypoint.sh"]